name: "Build and Push"
on:
  push:
  schedule:
    - cron: "0 19 * * SUN"
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: zenn-cli
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: |
          nix run nixpkgs.nodePackages.node2nix --command node2nix -i node-packages.json -c composition.nix
          nix-build -A zenn-cli | cachix push zenn-cli
