name: "Build and Push"
on:
  schedule:
    - cron: "0 19 * * SUN"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: zenn-cli
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run node2nix
        run: |
          nix run nixpkgs.nodePackages.node2nix --command node2nix -i node-packages.json -c composition.nix
      - name: Count changes
        id: count_changes
        # https://zenn.dev/snowcait/articles/18c9137f49e378
        run: |
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: Build and Push to Cachix
        if: steps.count_changes.outputs.count > 0
        run: nix-build -A zenn-cli | cachix push zenn-cli
      - name: Commit and Push to GitHub
        if: steps.count_changes.outputs.count > 0
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
